export const FETCH_PRODUCT_DETAIL_REQUEST = 'DETAIL/FETCH_PRODUCT_DETAIL_REQUEST';
export const FETCH_PRODUCT_DETAIL_SUCCESS = 'DETAIL/FETCH_PRODUCT_DETAIL_SUCCESS';
export const FETCH_PRODUCT_DETAIL_FAILURE = 'DETAIL/FETCH_PRODUCT_DETAIL_FAILURE';

export const FETCH_SHOP_REQUEST = 'DETAIL/FETCH_SHOP_REQUEST';
export const FETCH_SHOP_SUCCESS = 'DETAIL/FETCH_SHOP_SUCCESS';
export const FETCH_SHOP_FAILURE = 'DETAIL/FETCH_SHOP_FAILURE';