export const FETCH_INPUT_KEYWORDS_REQUEST = 'SEARCH/FETCH_INPUT_KEYWORDS_REQUEST';
export const FETCH_INPUT_KEYWORDS_SUCCESS = 'SEARCH/FETCH_INPUT_KEYWORDS_SUCCESS';
export const FETCH_INPUT_KEYWORDS_FAILURE = 'SEARCH/FETCH_INPUT_KEYWORDS_FAILURE';

export const SET_INPUT_KEYWORD_TEXT = 'SEARCH/SET_INPUT_KEYWORD_TEXT';
export const CLEAR_INPUT_KEYWORD_TEXT = 'SEARCH/CLEAR_INPUT_KEYWORD_TEXT';

export const ADD_HISTORY_KEYWORD_TEXT = 'SEARCH/ADD_HISTORY_KEYWORD_TEXT';
export const CLEAR_HISTORY_KEYWORD_TEXT = 'SEARCH/CLEAR_HISTORY_KEYWORD_TEXT';

export const SELECT_KEYWORD_TEXT = 'SEARCH/SELECT_KEYWORD_TEXT';