//The constants for recommend products list
export const FETCH_LIKES_REQUEST = 'HOME/FETCH_LIKES_REQUEST';
export const FETCH_LIKES_SUCCESS = 'HOME/FETCH_LIKES_SUCCESS';
export const FETCH_LIKES_FAILURE = 'HOME/FETCH_LIKES_FAILURE';

export const FETCH_DISCOUNTS_REQUEST = 'HOME/FETCH_DISCOUNTS_REQUEST';
export const FETCH_DISCOUNTS_SUCCESS = 'HOME/FETCH_DISCOUNTS_SUCCESS';
export const FETCH_DISCOUNTS_FAILURE = 'HOME/FETCH_DISCOUNTS_FAILURE';

export const params = {
    PATH_LIKES: "likes",
    PATH_DISCOUNTS: "discounts",
    PAGE_SIZE_LIKES: 5,
    PAGE_SIZE_DISCOUNTS: 3
  };