export const FETCH_RESULT_REQUEST = 'SEARCH_RESULT/FETCH_RESULT_REQUEST';
export const FETCH_RESULT_SUCCESS = 'SEARCH_RESULT/FETCH_RESULT_SUCCESS';
export const FETCH_RESULT_FAILURE = 'SEARCH_RESULT/FETCH_RESULT_FAILURE';