export const FETCH_USER_ORDER_REQUEST = 'USER/FETCH_USER_ORDER_REQUEST';
export const FETCH_USER_ORDER_SUCCESS = 'USER/FETCH_USER_ORDER_SUCCESS';
export const FETCH_USER_ORDER_FAILURE = 'USER/FETCH_USER_ORDER_FAILURE';